### ISSUE TITLE
 Uncaught Error: Class 'DOMDocument' not found in /usr/share/wp-cli/vendor/nb/oxymel/Oxymel.php:147

### ISSUE THREAD

**Issue by sandrodz** [soifou/wpcli-alpine#1]
It seems DOM extension is missing from alpine image.

This error happens when I am trying to export the page content e.g: 

`wp export --post_type=page --post__in=160 --path=/mnt/public/wordpress`

**Comment by soifou** [comment]
Hey @sandrodz thanks for the report, 

I just pushed to Docker hub an updated version of WP-CLI v1.5.1 with DOM extension (on latest tag).
Let me know if it's working.

**Comment by sandrodz** [comment]
It works, thanks! And extra thanks for the quick fix.
I've been using your container for years now. Was about to fork it, in case it was abandoned :) 

In case you are wondering:
https://github.com/wearede/DevCeption/blob/master/provisioning/roles/php-tools/files/wp
